### ISSUE TITLE
Where can I find some speckle pictures?

### ISSUE THREAD

**Issue by Johann-Faust** [DoctorEmmetBrown/popcorn#1]
Hello doctor, your summary of the speckle tracking algorithm is great, could you please share some speckle pictures in the file, such as some speckle pictures from your experiments, or if there is a related website where you can find such pictures, Now I can't test the software due to lack of speckle map (ref, sample). Thanks again for your software!

**Comment by DoctorEmmetBrown** [comment]
Hello
Many thanks for your interests in our software
You can find some data obtained on a conventional X-ray system over there :https://osf.io/4ruq2/  

We are preparing a manuscript comparing the different algorithms/methods and more data will be shared on this repository in a near future
